services:
  localstack:
    container_name: "localstack-nems-event-processor"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
      - GATEWAY_LISTEN=4566
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
