services:
  localstack:
    container_name: "localstack-ehr-repo-service"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,dynamodb,s3
      - DEFAULT_REGION=eu-west-2
      - GATEWAY_LISTEN=4566
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      - dynamodb-local:dynamodb-local
  dynamodb-local:
    network_mode: bridge
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "4573:8000"