name: Base Node Services Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - pre-prod
          - prod
        required: true
        default: dev
        description: Which environment to build and deploy to?
      service:
        type: choice
        options:
          - ehr-repo
        description: Which service to build and deploy
      is_deployment:
        type: boolean
        default: false
        description: Whether to deploy of not
      enable_end_to_end_testing:
        type: boolean
        default: false
        description: Whether to perform end to end tests
      skip_build_and_publish:
        type: boolean
        default: true
        description: Whether to skip build_and_publish step

  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      service:
        type: string
      is_deployment:
        type: boolean
        default: false
      enable_end_to_end_testing:
        type: boolean
        default: false
      skip_build_and_publish:
        type: boolean
        default: false

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  build_and_publish:
    if: ${{ !inputs.skip_build_and_publish && inputs.is_deployment }}
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: './services/${{ inputs.service }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: 22

      - name: Clean Install
        run: npm run build

      - name: Configure AWS Credentials (Read/Write)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login

      - name: Get ECR repository URI from SSM
        id: ecr-repo
#        TODO do we want to make sure the name of the ecr repos can match the services to aid in making things reusable?
        run: | 
          uri=$(aws ssm get-parameter \
          --name "/repo/${{ vars.AWS_ENVIRONMENT }}/prm-deductions-ehr-repository/ecr/url/${{ inputs.service }}" \
          --query "Parameter.Value" --output text)
          echo "::add-maks::$uri"
          echo "uri=$uri" >> $GITHUB_OUTPUT

      - name: docker build, tag, and publish
        env:
          REF_NAME: ${{ github.ref_name }}
          ECR_URI: ${{ steps.ecr-repo.outputs.uri }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          TAG_ARGS=(-t "$ECR_URI:$IMAGE_TAG" -t "$ECR_URI:latest")
          if [ -n "${REF_NAME:-}" ]; then
            REF_TAG="${REF_NAME//\//-}"
            TAG_ARGS+=(-t "$ECR_URI:$REF_TAG")
          fi

          docker build "${TAG_ARGS[@]}" --build-arg BUILD_TAG="$IMAGE_TAG" .

          docker push "$ECR_URI:$IMAGE_TAG"
          docker push "$ECR_URI:latest"

          if [ -n "${REF_NAME:-}" ]; then
            REF_TAG="${REF_NAME//\//-}"
            docker push "$ECR_URI:$REF_TAG"
          fi  
          
  deploy_infra:
    name: Deploy EHR Infrastructure
    uses: nhsconnect/prm-deductions-infra/.github/workflows/deploy-stack.yml@PRM-495
    with:
      stack: ${{ inputs.service }}
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  end_to_end_test:
    if: ${{ inputs.enable_end_to_end }}
    name: End to End
    needs: [deploy_infra]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit