# TODO double check permissions - AWS
# TODO where would/how would we like to promote images, use similar workflow from GP2GP repos?
name: Build & Publish EHR Repository

on:
  push:
    branches:
      - main
    paths:
      - 'services/ehr-repo/**'

  workflow_dispatch:
    inputs:
      environment:
        default: "dev"
        type: string
        description: "Environment to use"

  workflow_call:
    inputs:
      environment:
        default: "dev"
        type: string

permissions:
  contents: read  # Required for actions/checkout
  id-token: write # Required for requesting the JWT
  pull-requests: write # Required to write comments

jobs:
  build_and_publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: './services/ehr-repo'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean install
        run: npm ci

      - name: build
        run: npm run build

      - name: Configure AWS Credentials (Read Write)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get ECR repository URI from SSM
        id: ecr-repo
        run: |
          uri=$(aws ssm get-parameter \
          --name "/repo/${{ vars.AWS_ENVIRONMENT }}/prm-deductions-ehr-repository/ecr/url/ehr-repository" \
          --query "Parameter.Value" --output text)
          echo "::add-mask::$uri"
          echo "uri=$uri" >> $GITHUB_OUTPUT

      - name: docker build, tag, and publish
        env:
          REF_NAME: ${{ github.ref_name }}
          ECR_URI: ${{ steps.ecr-repo.outputs.uri }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          TAG_ARGS=(-t "$ECR_URI:$IMAGE_TAG" -t "$ECR_URI:latest")
          if [ -n "${REF_NAME:-}" ]; then
            REF_TAG="${REF_NAME//\//-}"
            TAG_ARGS+=(-t "$ECR_URI:$REF_TAG")
          fi

          docker build "${TAG_ARGS[@]}" --build-arg BUILD_TAG="$IMAGE_TAG" .

          docker push "$ECR_URI:$IMAGE_TAG"
          docker push "$ECR_URI:latest"

          if [ -n "${REF_NAME:-}" ]; then
            REF_TAG="${REF_NAME//\//-}"
            docker push "$ECR_URI:$REF_TAG"
          fi

  deploy_infra:
    name: Deploy EHR Infrastructure
    runs-on: ubuntu-latest
    needs: [build_and_publish]
    environment: ${{ inputs.environment }}

    # TODO once renaming of repositories and moving of Github org, this step will need adjusting to reflect repo change
    steps:
      - name: Checkout Infra
        uses: actions/checkout@v5
        with:
          repository: 'nhsconnect/prm-deductions-infra'
          ref: PRM-495  # e.g. dev, feature-xyz

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ECR_HOLDING_ACCOUNT_READ_WRITE }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Deploy Infrastructure
        uses: nhsconnect/prm-deductions-infra/.github/workflows/deploy-stack.yml@PRM-495
        with:
          stack: ehr-repo
          environment: ${{ inputs.environment }}
          is_deplyoment: true

  end_to_end_test:
    name: End to End
    needs: [deploy_infra]
    uses: ./.github/workflows/e2e.yml
  