name: Test Node Service
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.get_changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get Changes
        id: get_changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | tr '\n' ' ')
          echo "changed=$changed" >> $GITHUB_OUTPUT

  test_ehr_repo:
    name: Test EHR Repo
    needs: get_changed_files
    if: contains(needs.get_changed_files.outputs.changed, 'services/ehr-repo') || contains(needs.get_changed_files.outputs.changed, '.github/')
    uses: './.github/workflows/base-node-service-jobs.yml'
    with:
      service: ehr-repo

  test_ehr_out_service:
    needs: get_changed_files
    name: Test EHR Out Service
    if: contains(needs.get_changed_files.outputs.changed, 'services/ehr-out-service') || contains(needs.get_changed_files.outputs.changed, '.github/')
    uses: './.github/workflows/base-node-service-jobs.yml'
    with:
      service: ehr-out-service
