name: Services CI

on:
  push:
    branches:
      - main
    paths:
      - 'services/ehr-repo/**'
      - 'services/mesh-forwarder/**'
      - '.github/workflows/service-ci.yml'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'services/ehr-repo/**'
      - 'services/mesh-forwarder/**'
      - '.github/workflows/service-ci.yml'

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.get_changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get Changes
        id: get_changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | tr '\n' ' ')
          echo "changed=$changed" >> $GITHUB_OUTPUT
          
  ehr-repo:
    needs: get_changed_files
    if: contains(needs.get_changed_files.outputs.changed, 'services/ehr-repo') || contains(needs.get_changed_files.outputs.changed, '.github/')
    uses: './.github/workflows/base-node-service-jobs.yml'
    with:
      service: ehr-repo
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      skip_build_and_publish: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit

  mesh-inbox-s3-forwarder:
    needs: get_changed_files
    if: contains(needs.get_changed_files.outputs.changed, 'services/mesh-inbox-s3-forwarder') || contains(needs.get_changed_files.outputs.changed, '.github/')
    uses: './.github/workflows/base-python-service-jobs.yml'
    with:
      service: mesh-inbox-s3-forwarder
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      skip_build_and_publish: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit

  mesh-forwarder:
    needs: [ get_changed_files, mesh-inbox-s3-forwarder ]
    if: contains(needs.get_changed_files.outputs.changed, 'services/mesh-forwarder') || contains(needs.get_changed_files.outputs.changed, '.github/')
    uses: './.github/workflows/base-python-service-jobs.yml'
    with:
      service: mesh-forwarder
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      skip_build_and_publish: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit

  e2e-testing:
    name: End to End
    if: ${{ vars.E2E_TESTS_ENABLED == 'true' && success() }}
    needs: [ehr-repo]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
