name: Services CI

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/service-ci.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/service-ci.yml'

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.get_changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Changes
        id: get_changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | tr '\n' ' ')
          echo "changed=$changed" >> $GITHUB_OUTPUT

  ehr-repo:
    needs: get_changed_files
    if: contains(needs.get_changed_files.outputs.changed, 'services/ehr-repo') || contains(needs.get_changed_files.outputs.changed, '.github/')
    uses: './.github/workflows/base-node-service-jobs.yml'
    with:
      service: ehr-repo
      environment: dev
      is_deployment: ${{ github.ref == 'refs/heads/main' }}
      enable_end_to_end_testing: false
      skip_build_and_publish: ${{ github.ref != 'refs/heads/main' }}