name: Services CI

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/service-ci.yml'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/service-ci.yml'

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.get_changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get Changes
        id: get_changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          changed=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | tr '\n' ' ')
          echo "changed=$changed" >> $GITHUB_OUTPUT
          
  ehr-repo:
    needs: get_changed_files
    runs-on: ubuntu-latest
    if: contains(needs.get_changed_files.outputs.changed, 'services/ehr-repo') || contains(needs.get_changed_files.outputs.changed, '.github/')
    steps:
      - name: Test EHR Repo
        uses: './.github/workflows/test-node-service.yml'
        with:
          service: ehr-repo

      - name: EHR job
        uses: './.github/workflows/base-node-service-jobs.yml'
        with:
          service: ehr-repo
          environment: dev
          is_deployment: ${{ github.ref == 'refs/heads/main' }}
          skip_build_and_publish: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit

  ehr-out-service:
    needs: get_changed_files
    runs-on: ubuntu-latest
    if: contains(needs.get_changed_files.outputs.changed, 'services/ehr-out-service') || contains(needs.get_changed_files.outputs.changed, '.github/')
    steps:
      - name: Test EHR Repo
        uses: './.github/workflows/test-node-service.yml'
        with:
          service: ehr-out-service

      - name: EHR Out Service Job
        uses: './.github/workflows/base-node-service-jobs.yml'
        with:
          service: ehr-out-service
          environment: dev
          is_deployment: ${{ github.ref == 'refs/heads/main' }}
          skip_build_and_publish: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit

  e2e-testing:
    name: End to End
    if: ${{ vars.E2E_TESTS_ENABLED == 'true' && success() }}
    needs: [ehr-repo]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
